export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const GET_APPS = 'GET_APPS';
export const GET_USER_DATA = 'GET_USER_DATA';
